version: '3.8'

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build: .
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
